version: "3.9"

services:
  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network
  api:
    container_name: api
    restart: unless-stopped
    tty: true
    build:
      context: ./bitad-api/BitadAPI
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network
  frontend:
    container_name: frontend
    restart: unless-stopped
    tty: true
    build:
      context: ./bitad-frontend/
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - api
      - db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
